### PR TITLE
Adding tests and deleting old manifest

### PR DESCRIPTION
**Pull request by Shushman**
Changes:

* A basic set of tests for getters in `tests`. 
* The old `manifest.xml` file deleted. (before catkin build)

### CODE REVIEW

**Comment by mkoval** [comment]
Good start. Thanks!

**Comment by mkoval** [comment]
Actually, please:

1. Add `python` and `python-nosetest` as `<test_depend>`s in the `package.xml` file
2. Register the tests in the `CMakeLists.txt` file
3. Restore the `manifest.xml` file - we will remove that in a separate, atomic pull request

See our [unit testing guide](https://github.com/personalrobotics/pr_docs/wiki/PRL-Unit-Testing#writing-tests) for details about (1) and (2).

@Shushman Can you take care of this?

**Comment by Shushman** [comment]
@mkoval I've addressed the changes. Note that to successfully run the tests, the user must source `/opt/ros/indigo/setup.bash` and the workspace as well. That is supposed to be the case, right?

**Comment by mkoval** [comment]
Thanks @Shushman!

**Comment by mkoval** [comment]
Whoops, I forgot to answer your question:

> Note that to successfully run the tests, the user must source `/opt/ros/indigo/setup.bash` and the workspace as well. That is supposed to be the case, right?

That's fine. Anything in the workspace can safely assume that the user sourced the containing workspace's `setup.bash` file. Some executables may work despite this, but there are no guarantees.

You should **not** have to explicitly source `/opt/ros/indigo/setup.bash` because your workspace is (directly or indirectly) chained from it. To be safe, you should only ever source **one** `setup.bash` file per terminal window. This includes the one in `/opt/ros/indigo`.

**Pull request merged**
