### PR TITLE
Add support for parsing <link> <geom_group> elements in URDF

### PR DESCRIPTION
**Pull request by DavidB-CMU**
More info:
Issue 19: Add support for parsing custom link element \<geom_group>
personalrobotics/or_urdf#19

An updated URDF of the Barrett gripper is in pull request personalrobotics/herb_description#21

### CODE REVIEW

**Comment by psigen** [comment]
What happens if a urdf with the geom-group tag is loaded via the OSRF
urdfdom library (i.e. when using a robot model in rviz)?

Is it just ignored?

**Comment by DavidB-CMU** [comment]
In `or_urdf` it parses the URDF once using liburdfdom. 
Then it parses the SRDF file. 
The it parses the URDF again using tinyXML directly. 

So yes the tag is otherwise ignored, at least with our software stack. 
In Rviz (using `or_rviz`) I can toggle the various geometry groups.

Is that what you meant @psigen ?  or should I try to load `herb_description` into Rviz without using our software stack?

**Comment by mkoval** [comment]
:+1: For parsing the URDF once with `urdfdom` and a second time with TinyXML. I don't see any better way of doing this.

However, I am confused why you have to do two passes through the file with TinyXML. It seems like you could set all of the attributes in the first pass and remove the second pass entirely. What am I missing?

**Comment by psigen** [comment]
@DavidB-CMU: In reference to https://github.com/personalrobotics/or_urdf/pull/20#issuecomment-171175606

Yes, I'm thinking about what happens if we provide this URDF to another tool, such as loading it into the `robot_description` rosparam and trying to run things like RobotStatePublisher and RViz's `robot model` visualization, outside of `prpy` and `or_rviz`.

**Comment by dbworth** [comment]
Ok I will make those changes and checks.

@mkoval Actually, originally it was me that didn't want to do two passes with TinyXML but then you suggested it. 

Each link in the robot may have any number of \<geometry_group\> tags, or it may have none.
However, each link *must* be a member of all geometry groups in OpenRAVE. 
If a link is not specified to be part of a geometry group then it must be added to the geometry group with no geometry. 
If you don't do this then OpenRAVE crashes, so this is how the spheres group is created in the code we have already. 

The first pass makes a list of the names of the geometry groups, then in the second pass each link is added to each geometry group in the list - either with no geometry, or with the mesh specified in that link's \<geometry_group\> tag.

**Comment by DavidB-CMU** [comment]
Ok I will make those changes and checks.

@mkoval Actually, originally it was me that didn't want to do two passes with TinyXML but then you suggested it.

Each link in the robot may have any number of <geometry_group> tags, or it may have none.
However, each link must be a member of all geometry groups in OpenRAVE. 
If a link is not specified to be part of a geometry group then it must be added to the geometry group with no geometry. 
If you don't do this then OpenRAVE crashes, so this is how the spheres group is created in the code we have already.

The first pass makes a list of the names of the geometry groups, then in the second pass each link is added to each geometry group in the list - either with no geometry, or with the mesh specified in that link's <geometry_group> tag.

**Comment by mkoval** [comment]
> Actually, originally it was me that didn't want to do two passes with TinyXML but then you suggested it.

I think there was some miscommunication here. I was talking about parsing the XML file twice: once with `urdfdom` to load the standard attributes and once with `TinyXML` to load our custom extensions.

> The first pass makes a list of the names of the geometry groups, then in the second pass each link is added to each geometry group in the list - either with no geometry, or with the mesh specified in that link's tag.

The two passes are definitely required, but only one needs to parse XML. I suggest building `geom_groups_set` in the same pass that edits the `LinkInfo`s. The second pass is simply:
```c++
BOOST_FOREACH (OpenRAVE::KinBody::LinkInfoPtr candidate, link_infos)
    BOOST_FOREACH (std::string& geom_group_name, geom_groups_set)
        link_info->_mapExtraGeometries[geom_group_name];
```
I believe this is equivalent to the current implementation in roughly half the code.

It's possible that I'm still missing a subtly here - please don't hesitate to tell me that I'm wrong. :sweat:

**Comment by mkoval** [comment]
I'd also like to reiterate my comment in https://github.com/personalrobotics/herb_description that I'd prefer `geometry_group` to `geom_group`. We'll likely stick with the same tag format to load geometry groups into other software (e.g. DART), so I'd like to make this change before merging anything into `master`.

**Comment by DavidB-CMU** [comment]
You can see the robot geometry through OpenRAVE and or_rviz in the original ticket: https://github.com/personalrobotics/or_urdf/issues/19

And it also works if you load the URDF into the ROS `robot_description` parameter, then launch a `joint_state_publisher` and a `robot_state_publisher` :
herb_robot_model_in_rviz

Should we add this launch file to some package e.g. `herb_description` ?

**Comment by DavidB-CMU** [comment]
I changed the element name from <geom_group> to <geometry_group>.

**Comment by DavidB-CMU** [comment]
Regarding making only one pass of the URDF... 

Lets say a robot has 10 links. 
The first 8 links have no \<geometry_group\> tags.
The 9th link has  \<geometry_group name="blue"\> 
The 10th link has  \<geometry_group name="blue"\>  AND \<geometry_group name="orange"\> 

When I initially look at the 1st link, how do I know in advance that it needs to be added to two geometry groups?

**Comment by mkoval** [comment]
I understand that two passes are necessary. I'm asking that you only do one pass through the TinyXML document that: (1) creates geometry inside the `geometry_group` tags and (2) builds a `geom_groups_set` of all geometry groups that we found. The second pass just iterates through the `LinkInfo`s and creates the missing entries in `_mapExtraGeometries` (see the pseuocode above).

**Comment by psigen** [comment]
@DavidB-CMU: Thanks for verifying that it's all working in the rviz tools.  It's pretty cool that modifications like this are tolerated by the `urdfdom` library.

**Comment by DavidB-CMU** [comment]
Ok @mkoval we can now process the <geometry_group> tags by parsing the URDF only once. 

Previously you asked why it only supports one <geometry> element for each link. 
This is simply because that's what I need right now, and it's the only thing that I've tested. This information would be written in the documentation. 
Do you think we should immediately add support for multiple meshes in the one geometry group?

**Comment by mkoval** [comment]
I'm not sure that I follow - it seems like additional effort to support only one `<geometry>`.

That's find, though, because it's easy enough to add support for multiple geometries when we need it.

**Pull request merged**
